/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 22 15:04:41 GMT 2024
 */

package org.apache.commons.codec.language.bm;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.codec.language.bm.ResourceConstants;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ResourceConstants_ESTest extends ResourceConstants_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ResourceConstants resourceConstants0 = new ResourceConstants();
  }
}
