/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 22 14:22:20 GMT 2024
 */

package org.apache.commons.codec;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.codec.DecoderException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DecoderException_ESTest extends DecoderException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      DecoderException decoderException0 = new DecoderException((String) null, mockThrowable0);
  }
}
