/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 19:12:00 GMT 2025
 */

package org.apache.commons.codec.language.bm;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.NoSuchElementException;
import org.apache.commons.codec.language.bm.Languages;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Languages$AnyLanguage_ESTest extends Languages$AnyLanguage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Languages.AnyLanguage languages_AnyLanguage0 = new Languages.AnyLanguage();
      Languages.LanguageSet languages_LanguageSet0 = languages_AnyLanguage0.restrictTo(languages_AnyLanguage0);
      assertFalse(languages_LanguageSet0.isSingleton());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Languages.AnyLanguage languages_AnyLanguage0 = new Languages.AnyLanguage();
      boolean boolean0 = languages_AnyLanguage0.isSingleton();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Languages.AnyLanguage languages_AnyLanguage0 = new Languages.AnyLanguage();
      // Undeclared exception!
      try { 
        languages_AnyLanguage0.getAny();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Can't fetch any language from the any language set.
         //
         verifyException("org.apache.commons.codec.language.bm.Languages$AnyLanguage", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Languages.AnyLanguage languages_AnyLanguage0 = new Languages.AnyLanguage();
      boolean boolean0 = languages_AnyLanguage0.contains("ANY_LANGUAGE");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Languages.AnyLanguage languages_AnyLanguage0 = new Languages.AnyLanguage();
      boolean boolean0 = languages_AnyLanguage0.isEmpty();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Languages.AnyLanguage languages_AnyLanguage0 = new Languages.AnyLanguage();
      Languages.NoLanguage languages_NoLanguage0 = new Languages.NoLanguage();
      Languages.LanguageSet languages_LanguageSet0 = languages_AnyLanguage0.merge(languages_NoLanguage0);
      assertFalse(languages_LanguageSet0.isSingleton());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Languages.AnyLanguage languages_AnyLanguage0 = new Languages.AnyLanguage();
      String string0 = languages_AnyLanguage0.toString();
      assertEquals("ANY_LANGUAGE", string0);
  }
}
