/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 22 14:57:44 GMT 2024
 */

package org.apache.commons.graph.flow;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.graph.Mapper;
import org.apache.commons.graph.flow.DefaultFromHeadBuilder;
import org.apache.commons.graph.flow.ToTailBuilder;
import org.apache.commons.graph.model.DirectedMutableGraph;
import org.apache.commons.graph.model.RevertedGraph;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultFromHeadBuilder_ESTest extends DefaultFromHeadBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DirectedMutableGraph<Integer, Integer> directedMutableGraph0 = new DirectedMutableGraph<Integer, Integer>();
      RevertedGraph<Integer, Integer> revertedGraph0 = new RevertedGraph<Integer, Integer>(directedMutableGraph0);
      Mapper<Integer, Integer> mapper0 = (Mapper<Integer, Integer>) mock(Mapper.class, new ViolatedAssumptionAnswer());
      DefaultFromHeadBuilder<Integer, Integer, Integer> defaultFromHeadBuilder0 = new DefaultFromHeadBuilder<Integer, Integer, Integer>(revertedGraph0, mapper0);
      Integer integer0 = new Integer(974);
      ToTailBuilder<Integer, Integer, Integer> toTailBuilder0 = defaultFromHeadBuilder0.from(integer0);
      assertNotNull(toTailBuilder0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DirectedMutableGraph<Integer, Integer> directedMutableGraph0 = new DirectedMutableGraph<Integer, Integer>();
      DefaultFromHeadBuilder<Integer, Integer, Integer> defaultFromHeadBuilder0 = new DefaultFromHeadBuilder<Integer, Integer, Integer>(directedMutableGraph0, (Mapper<Integer, Integer>) null);
      // Undeclared exception!
      try { 
        defaultFromHeadBuilder0.from((Integer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // head vertex has to be specifies when looking for the max flow
         //
         verifyException("org.apache.commons.graph.utils.Assertions", e);
      }
  }
}
