/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 15 20:08:44 GMT 2024
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import me.lemire.integercompression.UncompressibleInputException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UncompressibleInputException_ESTest extends UncompressibleInputException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UncompressibleInputException uncompressibleInputException0 = new UncompressibleInputException("))0]. #");
  }
}
