/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 19:04:52 GMT 2025
 */

package org.apache.commons.graph.builder;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import org.apache.commons.graph.builder.DefaultLinkedConnectionBuilder;
import org.apache.commons.graph.builder.GraphConnection;
import org.apache.commons.graph.model.UndirectedMutableGraph;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultLinkedConnectionBuilder_ESTest extends DefaultLinkedConnectionBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultLinkedConnectionBuilder<Integer, Integer, UndirectedMutableGraph<Integer, Integer>> defaultLinkedConnectionBuilder0 = new DefaultLinkedConnectionBuilder<Integer, Integer, UndirectedMutableGraph<Integer, Integer>>((UndirectedMutableGraph<Integer, Integer>) null);
      GraphConnection<Integer, Integer> graphConnection0 = (GraphConnection<Integer, Integer>) mock(GraphConnection.class, new ViolatedAssumptionAnswer());
      UndirectedMutableGraph<Integer, Integer> undirectedMutableGraph0 = defaultLinkedConnectionBuilder0.withConnections(graphConnection0);
      assertNull(undirectedMutableGraph0);
  }
}
