/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 19:19:42 GMT 2025
 */

package org.apache.commons.graph;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.graph.CommonsGraph;
import org.apache.commons.graph.DirectedGraph;
import org.apache.commons.graph.Graph;
import org.apache.commons.graph.MutableGraph;
import org.apache.commons.graph.SynchronizedDirectedGraph;
import org.apache.commons.graph.SynchronizedMutableGraph;
import org.apache.commons.graph.SynchronizedUndirectedGraph;
import org.apache.commons.graph.UndirectedGraph;
import org.apache.commons.graph.builder.GraphConnection;
import org.apache.commons.graph.builder.LinkedConnectionBuilder;
import org.apache.commons.graph.elo.GameResult;
import org.apache.commons.graph.elo.RankingSelector;
import org.apache.commons.graph.export.NamedExportSelector;
import org.apache.commons.graph.flow.FlowWeightedEdgesBuilder;
import org.apache.commons.graph.model.DirectedMutableGraph;
import org.apache.commons.graph.model.UndirectedMutableGraph;
import org.apache.commons.graph.scc.SccAlgorithmSelector;
import org.apache.commons.graph.shortestpath.PathWeightedEdgesBuilder;
import org.apache.commons.graph.spanning.SpanningWeightedEdgeMapperBuilder;
import org.apache.commons.graph.visit.VisitSourceSelector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CommonsGraph_ESTest extends CommonsGraph_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GraphConnection<Object, Object> graphConnection0 = (GraphConnection<Object, Object>) mock(GraphConnection.class, new ViolatedAssumptionAnswer());
      UndirectedMutableGraph<Object, Object> undirectedMutableGraph0 = CommonsGraph.newUndirectedMutableGraph(graphConnection0);
      VisitSourceSelector<Object, Object, MutableGraph<Object, Object>> visitSourceSelector0 = CommonsGraph.visit((MutableGraph<Object, Object>) undirectedMutableGraph0);
      assertNotNull(visitSourceSelector0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GraphConnection<Object, Object> graphConnection0 = (GraphConnection<Object, Object>) mock(GraphConnection.class, new ViolatedAssumptionAnswer());
      UndirectedMutableGraph<Object, Object> undirectedMutableGraph0 = CommonsGraph.newUndirectedMutableGraph(graphConnection0);
      Object object0 = new Object();
      undirectedMutableGraph0.addVertex(object0);
      Graph<Object, Object> graph0 = CommonsGraph.synchronize3((UndirectedGraph<Object, Object>) undirectedMutableGraph0);
      assertEquals(0, graph0.getSize());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GraphConnection<Object, Object> graphConnection0 = (GraphConnection<Object, Object>) mock(GraphConnection.class, new ViolatedAssumptionAnswer());
      DirectedMutableGraph<Object, Object> directedMutableGraph0 = CommonsGraph.newDirectedMutableGraph(graphConnection0);
      Object object0 = new Object();
      directedMutableGraph0.addVertex(object0);
      Graph<Object, Object> graph0 = CommonsGraph.synchronize2((MutableGraph<Object, Object>) directedMutableGraph0);
      assertEquals(1, graph0.getOrder());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GraphConnection<Object, Object> graphConnection0 = (GraphConnection<Object, Object>) mock(GraphConnection.class, new ViolatedAssumptionAnswer());
      DirectedMutableGraph<Object, Object> directedMutableGraph0 = CommonsGraph.newDirectedMutableGraph(graphConnection0);
      Object object0 = new Object();
      directedMutableGraph0.addVertex(object0);
      directedMutableGraph0.addEdge(object0, object0, object0);
      SynchronizedUndirectedGraph<Object, Object> synchronizedUndirectedGraph0 = new SynchronizedUndirectedGraph<Object, Object>(directedMutableGraph0);
      Graph<Object, Object> graph0 = CommonsGraph.synchronize1((Graph<Object, Object>) synchronizedUndirectedGraph0);
      assertEquals(1, graph0.getOrder());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      UndirectedMutableGraph<Object, Object> undirectedMutableGraph0 = new UndirectedMutableGraph<Object, Object>();
      Object object0 = new Object();
      undirectedMutableGraph0.addVertex(object0);
      Graph<Object, Object> graph0 = CommonsGraph.synchronize1((Graph<Object, Object>) undirectedMutableGraph0);
      assertEquals(0, graph0.getSize());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GraphConnection<Object, Object> graphConnection0 = (GraphConnection<Object, Object>) mock(GraphConnection.class, new ViolatedAssumptionAnswer());
      UndirectedMutableGraph<Object, Object> undirectedMutableGraph0 = CommonsGraph.newUndirectedMutableGraph(graphConnection0);
      SynchronizedMutableGraph<Object, Object> synchronizedMutableGraph0 = new SynchronizedMutableGraph<Object, Object>(undirectedMutableGraph0);
      LinkedConnectionBuilder<Object, Object, SynchronizedMutableGraph<Object, Object>> linkedConnectionBuilder0 = CommonsGraph.populate(synchronizedMutableGraph0);
      assertNotNull(linkedConnectionBuilder0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DirectedMutableGraph<Object, Object> directedMutableGraph0 = new DirectedMutableGraph<Object, Object>();
      SynchronizedDirectedGraph<Object, Object> synchronizedDirectedGraph0 = new SynchronizedDirectedGraph<Object, Object>(directedMutableGraph0);
      PathWeightedEdgesBuilder<Object, Object> pathWeightedEdgesBuilder0 = CommonsGraph.findShortestPath(synchronizedDirectedGraph0);
      assertNotNull(pathWeightedEdgesBuilder0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DirectedMutableGraph<Object, Object> directedMutableGraph0 = new DirectedMutableGraph<Object, Object>();
      FlowWeightedEdgesBuilder<Object, Object> flowWeightedEdgesBuilder0 = CommonsGraph.findMaxFlow((DirectedGraph<Object, Object>) directedMutableGraph0);
      assertNotNull(flowWeightedEdgesBuilder0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DirectedMutableGraph<Object, Object> directedMutableGraph0 = new DirectedMutableGraph<Object, Object>();
      NamedExportSelector<Object, Object> namedExportSelector0 = CommonsGraph.export((DirectedGraph<Object, Object>) directedMutableGraph0);
      assertNotNull(namedExportSelector0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DirectedMutableGraph<Object, GameResult> directedMutableGraph0 = new DirectedMutableGraph<Object, GameResult>();
      RankingSelector<Object> rankingSelector0 = CommonsGraph.eloRate((DirectedGraph<Object, GameResult>) directedMutableGraph0);
      assertNotNull(rankingSelector0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try { 
        CommonsGraph.newDirectedMutableGraph((GraphConnection<Object, UndirectedGraph<Object, Object>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Input graph cannot be configured with null connections
         //
         verifyException("org.apache.commons.graph.utils.Assertions", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try { 
        CommonsGraph.minimumSpanningTree((SynchronizedUndirectedGraph<Object, Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Minimum spanning tree can not be calculated on null graph
         //
         verifyException("org.apache.commons.graph.utils.Assertions", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        CommonsGraph.findStronglyConnectedComponent((DirectedGraph<SynchronizedDirectedGraph<SynchronizedDirectedGraph, Object>, Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Strongly Connected Component cannot be calculated from a null graph
         //
         verifyException("org.apache.commons.graph.utils.Assertions", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      // Undeclared exception!
      try { 
        CommonsGraph.populate((MutableGraph<MutableGraph<MutableGraph, Object>, Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Impossible to configure null graph!
         //
         verifyException("org.apache.commons.graph.utils.Assertions", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      // Undeclared exception!
      try { 
        CommonsGraph.visit((Graph<Graph<Object, Object>, Graph<Object, Graph>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // No algorithm can be applied on null graph!
         //
         verifyException("org.apache.commons.graph.utils.Assertions", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      GraphConnection<Object, Object> graphConnection0 = (GraphConnection<Object, Object>) mock(GraphConnection.class, new ViolatedAssumptionAnswer());
      UndirectedMutableGraph<Object, Object> undirectedMutableGraph0 = CommonsGraph.newUndirectedMutableGraph(graphConnection0);
      Graph<Object, Object> graph0 = CommonsGraph.synchronize3((UndirectedGraph<Object, Object>) undirectedMutableGraph0);
      assertEquals(0, graph0.getSize());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      GraphConnection<Object, Object> graphConnection0 = (GraphConnection<Object, Object>) mock(GraphConnection.class, new ViolatedAssumptionAnswer());
      DirectedMutableGraph<Object, Object> directedMutableGraph0 = CommonsGraph.newDirectedMutableGraph(graphConnection0);
      SynchronizedDirectedGraph<Object, Object> synchronizedDirectedGraph0 = new SynchronizedDirectedGraph<Object, Object>(directedMutableGraph0);
      SccAlgorithmSelector<Object, Object> sccAlgorithmSelector0 = CommonsGraph.findStronglyConnectedComponent(synchronizedDirectedGraph0);
      assertNotNull(sccAlgorithmSelector0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      // Undeclared exception!
      try { 
        CommonsGraph.export((DirectedGraph<Object, Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Null graph can not be exported
         //
         verifyException("org.apache.commons.graph.utils.Assertions", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      GraphConnection<Object, Object> graphConnection0 = (GraphConnection<Object, Object>) mock(GraphConnection.class, new ViolatedAssumptionAnswer());
      DirectedMutableGraph<Object, Object> directedMutableGraph0 = CommonsGraph.newDirectedMutableGraph(graphConnection0);
      SynchronizedDirectedGraph<Object, Object> synchronizedDirectedGraph0 = new SynchronizedDirectedGraph<Object, Object>(directedMutableGraph0);
      SpanningWeightedEdgeMapperBuilder<Object, Object> spanningWeightedEdgeMapperBuilder0 = CommonsGraph.minimumSpanningTree((DirectedGraph<Object, Object>) synchronizedDirectedGraph0);
      assertNotNull(spanningWeightedEdgeMapperBuilder0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      // Undeclared exception!
      try { 
        CommonsGraph.newUndirectedMutableGraph((GraphConnection<Object, Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Input graph cannot be configured with null connections
         //
         verifyException("org.apache.commons.graph.utils.Assertions", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      // Undeclared exception!
      try { 
        CommonsGraph.findConnectedComponent((Graph<DirectedGraph<DirectedGraph, Object>, DirectedGraph<Object, Object>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Connected Component cannot be calculated from a null graph
         //
         verifyException("org.apache.commons.graph.utils.Assertions", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      // Undeclared exception!
      try { 
        CommonsGraph.coloring((UndirectedGraph<SynchronizedDirectedGraph<SynchronizedDirectedGraph, SynchronizedDirectedGraph>, Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Coloring can not be calculated on null graph
         //
         verifyException("org.apache.commons.graph.utils.Assertions", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      // Undeclared exception!
      try { 
        CommonsGraph.findMaxFlow((DirectedGraph<Object, SynchronizedUndirectedGraph<Object, Object>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Max flow can not be calculated on null graph
         //
         verifyException("org.apache.commons.graph.utils.Assertions", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      // Undeclared exception!
      try { 
        CommonsGraph.eloRate((DirectedGraph<DirectedGraph<DirectedGraph, Object>, GameResult>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // ELO ranking can not be applied on null graph!
         //
         verifyException("org.apache.commons.graph.utils.Assertions", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      // Undeclared exception!
      try { 
        CommonsGraph.findShortestPath((SynchronizedDirectedGraph<Object, Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Shortest path can not be calculated on null graph
         //
         verifyException("org.apache.commons.graph.utils.Assertions", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      GraphConnection<Object, Object> graphConnection0 = (GraphConnection<Object, Object>) mock(GraphConnection.class, new ViolatedAssumptionAnswer());
      DirectedMutableGraph<Object, Object> directedMutableGraph0 = CommonsGraph.newDirectedMutableGraph(graphConnection0);
      SynchronizedUndirectedGraph<Object, Object> synchronizedUndirectedGraph0 = new SynchronizedUndirectedGraph<Object, Object>(directedMutableGraph0);
      Graph<Object, Object> graph0 = CommonsGraph.synchronize1((Graph<Object, Object>) synchronizedUndirectedGraph0);
      assertEquals(0, graph0.getSize());
  }
}
