/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 18:46:58 GMT 2025
 */

package org.apache.commons.fileupload;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedInputStream;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.io.PushbackInputStream;
import java.io.SequenceInputStream;
import java.util.Enumeration;
import org.apache.commons.fileupload.MultipartStream;
import org.apache.commons.fileupload.ProgressListener;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFileInputStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MultipartStream_ESTest extends MultipartStream_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      byte[] byteArray0 = new byte[11];
      byteArray0[4] = (byte)14;
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      byte[] byteArray1 = new byte[2];
      ProgressListener progressListener0 = mock(ProgressListener.class, new ViolatedAssumptionAnswer());
      MultipartStream.ProgressNotifier multipartStream_ProgressNotifier0 = new MultipartStream.ProgressNotifier(progressListener0, (byte)0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream2(byteArrayInputStream0, byteArray1, multipartStream_ProgressNotifier0);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      long long0 = multipartStream_ItemInputStream0.skip((byte)13);
      assertEquals(0, byteArrayInputStream0.available());
      assertEquals(5L, long0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, 303, (-772));
      BufferedInputStream bufferedInputStream0 = new BufferedInputStream(byteArrayInputStream0, 579);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(bufferedInputStream0, byteArray0);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.new ItemInputStream();
      try { 
        multipartStream_ItemInputStream0.read1(byteArray0, 45, (-1215));
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Stream ended unexpectedly
         //
         verifyException("org.apache.commons.fileupload.MultipartStream$ItemInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      byteArray0[2] = (byte)4;
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray0);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      multipartStream0.readByte();
      multipartStream0.readByte();
      int int0 = multipartStream_ItemInputStream0.read0();
      assertEquals(1L, multipartStream_ItemInputStream0.getBytesRead());
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(pipedInputStream0, byteArray0);
      int int0 = multipartStream0.findByte((byte)0, (byte)0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      boolean boolean0 = MultipartStream.arrayequals(byteArray0, byteArray0, 1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      byteArray0[4] = (byte)14;
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray0);
      try { 
        multipartStream0.readHeaders();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Stream ended unexpectedly
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      InputStream inputStream0 = InputStream.nullInputStream();
      BufferedInputStream bufferedInputStream0 = new BufferedInputStream(inputStream0, 2058);
      byte[] byteArray0 = new byte[15];
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(bufferedInputStream0, byteArray0);
      byte[] byteArray1 = new byte[3];
      try { 
        multipartStream0.setBoundary(byteArray1);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // The length of a boundary token cannot be changed
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      byte[] byteArray0 = new byte[5];
      BufferedInputStream bufferedInputStream0 = new BufferedInputStream(pipedInputStream0, 8);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream1(bufferedInputStream0, byteArray0, 10);
      assertEquals((byte)13, MultipartStream.CR);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MultipartStream.ProgressNotifier multipartStream_ProgressNotifier0 = new MultipartStream.ProgressNotifier((ProgressListener) null, (-2028L));
      multipartStream_ProgressNotifier0.noteBytesRead(10240);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      byte[] byteArray0 = new byte[5];
      MultipartStream multipartStream0 = MultipartStream.MultipartStream1(pipedInputStream0, byteArray0, (byte)13);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      try { 
        multipartStream_ItemInputStream0.read();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray0);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      int int0 = multipartStream_ItemInputStream0.available();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      byteArray0[1] = (byte) (-26);
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray0);
      multipartStream0.readByte();
      byte byte0 = multipartStream0.readByte();
      assertEquals(0, byteArrayInputStream0.available());
      assertEquals((byte) (-26), byte0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      byte[] byteArray1 = MultipartStream.BOUNDARY_PREFIX;
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray1);
      multipartStream0.readByte();
      int int0 = multipartStream0.findSeparator();
      assertEquals(0, byteArrayInputStream0.available());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PipedInputStream pipedInputStream0 = new PipedInputStream(pipedOutputStream0, 913);
      byte[] byteArray0 = new byte[6];
      MultipartStream multipartStream0 = MultipartStream.MultipartStream2(pipedInputStream0, byteArray0, (MultipartStream.ProgressNotifier) null);
      int int0 = multipartStream0.findSeparator();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3((InputStream) null, byteArray0);
      // Undeclared exception!
      try { 
        multipartStream0.readHeaders();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray0);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      MultipartStream multipartStream1 = MultipartStream.MultipartStream1(multipartStream_ItemInputStream0, byteArray0, (byte)13);
      try { 
        multipartStream1.readByte();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Stream ended unexpectedly
         //
         verifyException("org.apache.commons.fileupload.MultipartStream$ItemInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3((InputStream) null, byteArray0);
      // Undeclared exception!
      try { 
        multipartStream0.readByte();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      // Undeclared exception!
      try { 
        MultipartStream.MultipartStream3(byteArrayInputStream0, (byte[]) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // boundary may not be null
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      // Undeclared exception!
      try { 
        MultipartStream.MultipartStream1(pipedInputStream0, byteArray0, (-2587));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The buffer size specified for the MultipartStream is too small
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray0);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      multipartStream0.readByte();
      try { 
        multipartStream_ItemInputStream0.close0();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Stream ended unexpectedly
         //
         verifyException("org.apache.commons.fileupload.MultipartStream$ItemInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      ProgressListener progressListener0 = mock(ProgressListener.class, new ViolatedAssumptionAnswer());
      MultipartStream.ProgressNotifier multipartStream_ProgressNotifier0 = new MultipartStream.ProgressNotifier(progressListener0, (byte)0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream2(byteArrayInputStream0, byteArray0, multipartStream_ProgressNotifier0);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      multipartStream0.readByte();
      int int0 = multipartStream_ItemInputStream0.read0();
      assertEquals(0, byteArrayInputStream0.available());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      byte[] byteArray0 = new byte[11];
      byteArray0[9] = (byte) (-1);
      byteArray0[4] = (byte)14;
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      PushbackInputStream pushbackInputStream0 = new PushbackInputStream(byteArrayInputStream0);
      byte[] byteArray1 = new byte[2];
      ProgressListener progressListener0 = mock(ProgressListener.class, new ViolatedAssumptionAnswer());
      MultipartStream.ProgressNotifier multipartStream_ProgressNotifier0 = new MultipartStream.ProgressNotifier(progressListener0, (byte)0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream2(pushbackInputStream0, byteArray1, multipartStream_ProgressNotifier0);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      long long0 = multipartStream_ItemInputStream0.skip(0L);
      assertEquals(0, byteArrayInputStream0.available());
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream1(byteArrayInputStream0, byteArray0, 1779);
      multipartStream0.readByte();
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      try { 
        multipartStream_ItemInputStream0.read1(byteArray0, (byte)10, 1779);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Stream ended unexpectedly
         //
         verifyException("org.apache.commons.fileupload.MultipartStream$ItemInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      byteArray0[1] = (byte)106;
      byte[] byteArray1 = new byte[7];
      boolean boolean0 = MultipartStream.arrayequals(byteArray0, byteArray1, (byte)10);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, 303, (-772));
      BufferedInputStream bufferedInputStream0 = new BufferedInputStream(byteArrayInputStream0, 579);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(bufferedInputStream0, byteArray0);
      try { 
        multipartStream0.readByte();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // No more data is available
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Enumeration<MockFileInputStream> enumeration0 = (Enumeration<MockFileInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      ProgressListener progressListener0 = mock(ProgressListener.class, new ViolatedAssumptionAnswer());
      MultipartStream.ProgressNotifier multipartStream_ProgressNotifier0 = new MultipartStream.ProgressNotifier(progressListener0, 1L);
      MultipartStream multipartStream0 = null;
      try {
        multipartStream0 = new MultipartStream(sequenceInputStream0, (byte[]) null, 0, multipartStream_ProgressNotifier0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // boundary may not be null
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      InputStream inputStream0 = InputStream.nullInputStream();
      MultipartStream.ProgressNotifier multipartStream_ProgressNotifier0 = new MultipartStream.ProgressNotifier((ProgressListener) null, (-1L));
      // Undeclared exception!
      try { 
        MultipartStream.MultipartStream2(inputStream0, (byte[]) null, multipartStream_ProgressNotifier0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // boundary may not be null
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Enumeration<MockFileInputStream> enumeration0 = (Enumeration<MockFileInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      byte[] byteArray0 = new byte[9];
      ProgressListener progressListener0 = mock(ProgressListener.class, new ViolatedAssumptionAnswer());
      MultipartStream.ProgressNotifier multipartStream_ProgressNotifier0 = new MultipartStream.ProgressNotifier(progressListener0, 689L);
      MultipartStream multipartStream0 = new MultipartStream(sequenceInputStream0, byteArray0, 3109, multipartStream_ProgressNotifier0);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      multipartStream_ItemInputStream0.isClosed();
      assertEquals(0, multipartStream_ItemInputStream0.available());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      MultipartStream.MalformedStreamException multipartStream_MalformedStreamException0 = new MultipartStream.MalformedStreamException("");
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      MultipartStream.IllegalBoundaryException multipartStream_IllegalBoundaryException0 = new MultipartStream.IllegalBoundaryException("");
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      byte[] byteArray1 = MultipartStream.BOUNDARY_PREFIX;
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray1);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      // Undeclared exception!
      try { 
        multipartStream_ItemInputStream0.read1(byteArray0, 10240, 1569);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      byte[] byteArray1 = byteArrayInputStream0.readNBytes((int) (byte)0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray1);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      try { 
        multipartStream_ItemInputStream0.close0();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Stream ended unexpectedly
         //
         verifyException("org.apache.commons.fileupload.MultipartStream$ItemInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      byte[] byteArray1 = byteArrayInputStream0.readNBytes((int) (byte)0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray1);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      multipartStream_ItemInputStream0.read1(byteArray0, (byte)0, 10240);
      try { 
        multipartStream_ItemInputStream0.read0();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Stream ended unexpectedly
         //
         verifyException("org.apache.commons.fileupload.MultipartStream$ItemInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray0);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.new ItemInputStream();
      multipartStream_ItemInputStream0.read1(byteArray0, (byte)0, (byte)0);
      assertEquals(0, multipartStream_ItemInputStream0.available());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      byteArray0[2] = (byte) (-1);
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray0);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      multipartStream0.readByte();
      multipartStream0.readByte();
      int int0 = multipartStream_ItemInputStream0.read0();
      assertEquals(0, byteArrayInputStream0.available());
      assertEquals(255, int0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      byte[] byteArray1 = byteArrayInputStream0.readNBytes((int) (byte)0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray1);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      multipartStream_ItemInputStream0.read0();
      multipartStream0.readByte();
      try { 
        multipartStream_ItemInputStream0.read0();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Stream ended unexpectedly
         //
         verifyException("org.apache.commons.fileupload.MultipartStream$ItemInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      byte[] byteArray0 = new byte[5];
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(pipedInputStream0, byteArray0);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      multipartStream_ItemInputStream0.close1(true);
      MultipartStream multipartStream1 = MultipartStream.MultipartStream1(multipartStream_ItemInputStream0, byteArray0, 456);
      try { 
        multipartStream1.readHeaders();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Stream ended unexpectedly
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      byte[] byteArray1 = MultipartStream.BOUNDARY_PREFIX;
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray1);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      long long0 = multipartStream_ItemInputStream0.skip((-1133L));
      assertEquals(0, byteArrayInputStream0.available());
      assertEquals((-1133L), long0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray0);
      // Undeclared exception!
      try { 
        multipartStream0.findByte((byte)0, (-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -1 out of bounds for length 4096
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray0);
      int int0 = multipartStream0.findByte((byte)84, (byte)84);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      // Undeclared exception!
      try { 
        MultipartStream.arrayequals(byteArray0, byteArray0, 3);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      boolean boolean0 = MultipartStream.arrayequals(byteArray0, byteArray0, (byte) (-114));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      byte[] byteArray0 = new byte[5];
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(pipedInputStream0, byteArray0);
      multipartStream0.setBoundary(byteArray0);
      assertEquals((byte)13, MultipartStream.CR);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray0);
      try { 
        multipartStream0.readBoundary();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Stream ended unexpectedly
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      MultipartStream.ProgressNotifier multipartStream_ProgressNotifier0 = new MultipartStream.ProgressNotifier((ProgressListener) null, (byte)13);
      MultipartStream multipartStream0 = null;
      try {
        multipartStream0 = new MultipartStream(pipedInputStream0, byteArray0, (-76), multipartStream_ProgressNotifier0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The buffer size specified for the MultipartStream is too small
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      byte[] byteArray0 = new byte[5];
      byte[] byteArray1 = new byte[1];
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(pipedInputStream0, byteArray1);
      try { 
        multipartStream0.setBoundary(byteArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // The length of a boundary token cannot be changed
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray0);
      multipartStream0.setHeaderEncoding("");
      assertEquals("", multipartStream0.getHeaderEncoding());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray0);
      String string0 = multipartStream0.getHeaderEncoding();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      // Undeclared exception!
      try { 
        MultipartStream.MultipartStream0();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // boundary may not be null
         //
         verifyException("org.apache.commons.fileupload.MultipartStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      MultipartStream multipartStream0 = MultipartStream.MultipartStream3(byteArrayInputStream0, byteArray0);
      MultipartStream.ItemInputStream multipartStream_ItemInputStream0 = multipartStream0.newInputStream();
      multipartStream_ItemInputStream0.getBytesRead();
      assertEquals(0, multipartStream_ItemInputStream0.available());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      MultipartStream.ProgressNotifier multipartStream_ProgressNotifier0 = new MultipartStream.ProgressNotifier((ProgressListener) null, (byte)13);
      multipartStream_ProgressNotifier0.noteItem();
  }
}
