/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 12 04:20:34 GMT 2024
 */

package org.fusesource.jansi.io;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.OutputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.fusesource.jansi.io.WindowsAnsiProcessor;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class WindowsAnsiProcessor_ESTest extends WindowsAnsiProcessor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WindowsAnsiProcessor windowsAnsiProcessor0 = null;
      try {
        windowsAnsiProcessor0 = new WindowsAnsiProcessor((OutputStream) null, 15L);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class org.fusesource.jansi.internal.Kernel32$CONSOLE_SCREEN_BUFFER_INFO
         //
         verifyException("org.fusesource.jansi.io.WindowsAnsiProcessor", e);
      }
  }
}
