/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 18:59:05 GMT 2025
 */

package me.lemire.integercompression;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.lemire.integercompression.DeltaZigzagBinaryPacking;
import me.lemire.integercompression.IntWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DeltaZigzagBinaryPacking_ESTest extends DeltaZigzagBinaryPacking_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[8];
      intArray0[1] = 1578;
      intArray0[2] = 1;
      IntWrapper intWrapper0 = new IntWrapper(1);
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.uncompress0(intArray0, intWrapper0, 8, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("me.lemire.integercompression.DeltaZigzagEncoding$Decoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[8];
      intArray0[3] = 63;
      intArray0[4] = 844;
      IntWrapper intWrapper0 = new IntWrapper(1);
      deltaZigzagBinaryPacking0.uncompress0(intArray0, intWrapper0, 8, intArray0, intWrapper0);
      intWrapper0.add(1);
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.uncompress0(intArray0, intWrapper0, 24, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 8 out of bounds for length 8
         //
         verifyException("me.lemire.integercompression.BitPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      IntWrapper intWrapper0 = IntWrapper.IntWrapper1();
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[5];
      intArray0[0] = 131071;
      intArray0[1] = 131071;
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.uncompress0(intArray0, intWrapper0, 131071, intArray0, intWrapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported bit width.
         //
         verifyException("me.lemire.integercompression.BitPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[4];
      intArray0[0] = 24;
      IntWrapper intWrapper0 = new IntWrapper(1);
      deltaZigzagBinaryPacking0.compress0(intArray0, intWrapper0, (-314), intArray0, intWrapper0);
      IntWrapper intWrapper1 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.uncompress0(intArray0, intWrapper1, (-314), intArray0, intWrapper1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported bit width.
         //
         verifyException("me.lemire.integercompression.BitPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[4];
      intArray0[0] = 19;
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntWrapper intWrapper1 = new IntWrapper((-445));
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.uncompress0(intArray0, intWrapper0, Integer.MAX_VALUE, intArray0, intWrapper1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -445 out of bounds for length 4
         //
         verifyException("me.lemire.integercompression.DeltaZigzagEncoding$Decoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[9];
      intArray0[0] = 1303;
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.uncompress0(intArray0, intWrapper0, 64, (int[]) null, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.DeltaZigzagEncoding$Decoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int[] intArray0 = new int[8];
      intArray0[0] = (-801);
      IntWrapper intWrapper0 = new IntWrapper(0);
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      deltaZigzagBinaryPacking0.uncompress0(intArray0, intWrapper0, (-801), intArray0, intWrapper0);
      assertEquals(1, intWrapper0.intValue());
      assertEquals((byte)1, intWrapper0.byteValue());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[3];
      IntWrapper intWrapper0 = new IntWrapper(0);
      IntWrapper intWrapper1 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.compress0(intArray0, intWrapper1, 2965, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 3 out of bounds for length 3
         //
         verifyException("me.lemire.integercompression.DeltaZigzagEncoding$Encoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[1];
      IntWrapper intWrapper0 = new IntWrapper(0);
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.compress0(intArray0, (IntWrapper) null, (-768), intArray0, intWrapper0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("me.lemire.integercompression.DeltaZigzagBinaryPacking", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[1];
      IntWrapper intWrapper0 = new IntWrapper(0);
      int[] intArray1 = new int[7];
      // Undeclared exception!
      try { 
        deltaZigzagBinaryPacking0.compress0(intArray1, intWrapper0, 199, intArray0, intWrapper0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 7 out of bounds for length 7
         //
         verifyException("me.lemire.integercompression.DeltaZigzagEncoding$Encoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[0];
      IntWrapper intWrapper0 = new IntWrapper(0);
      deltaZigzagBinaryPacking0.uncompress0(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals(0, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      int[] intArray0 = new int[4];
      IntWrapper intWrapper0 = new IntWrapper(0);
      deltaZigzagBinaryPacking0.compress0(intArray0, intWrapper0, 0, intArray0, intWrapper0);
      assertEquals((byte)0, intWrapper0.byteValue());
      assertEquals(0L, intWrapper0.longValue());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DeltaZigzagBinaryPacking deltaZigzagBinaryPacking0 = new DeltaZigzagBinaryPacking();
      String string0 = deltaZigzagBinaryPacking0.toString();
      assertEquals("DeltaZigzagBinaryPacking", string0);
  }
}
