/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 18:44:15 GMT 2025
 */

package org.apache.commons.exec;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ShutdownHookProcessDestroyer$ProcessDestroyerThread_ESTest extends ShutdownHookProcessDestroyer$ProcessDestroyerThread_ESTest_scaffolding {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
