models:
  gpt-4o-2024-11-20:
    model_id: gpt-4o-2024-11-20
    base_url:
    api_key: "PASTE YOUR API KEY HERE"
    default_headers: {}
    total: 128000
    max_new_tokens: 16384
  deepseek-coder-33b-instruct:
    model_id: deepseek-coder:33b
    base_url: "http://127.0.0.1:11434/v1"
    api_key: "PASTE YOUR API KEY HERE, IF REQUIRED"
    default_headers: {}
    total: 16384
    max_new_tokens: 4096
  llama-3-3-70b-instruct:
    model_id: llama-3-3-70b-instruct
    base_url: "PASTE YOUR MODEL ENDPOINT HERE"
    api_key: "PASTE YOUR API KEY HERE, IF REQUIRED"
    default_headers: {}
    total: 131072
    max_new_tokens: 16384
