/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 21:27:58 GMT 2025
 */

package org.apache.commons.validator.routines;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.apache.commons.validator.routines.DomainValidator;
import org.apache.commons.validator.routines.EmailValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class EmailValidator_ESTest extends EmailValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EmailValidator emailValidator0 = EmailValidator.getInstance1(false, false);
      boolean boolean0 = emailValidator0.isValidUser("(((\\.)|[^sp{Cntrl}()<>@,;:'\\\".[]]|')+|(\"(\\\"|[^\"])*\"))");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance1(true);
      EmailValidator emailValidator0 = new EmailValidator(1, false, true, domainValidator0);
      boolean boolean0 = emailValidator0.isValidUser("tunes");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      EmailValidator emailValidator0 = EmailValidator.getInstance0();
      // Undeclared exception!
      try { 
        emailValidator0.isValidDomain((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      EmailValidator emailValidator0 = EmailValidator.getInstance2(true);
      boolean boolean0 = emailValidator0.isValidUser(".^(((\\.)|[^sp{Cntrl}()<>@,;:'\\\".[]]|')+|(\"(\\\"|[^\"])*\"))(.(((\\.)|[^sp{Cntrl}()<>@,;:'\\\".[]]|')+|(\"(\\\"|[^\"])*\")))*$");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      EmailValidator emailValidator0 = EmailValidator.getInstance1(true, true);
      boolean boolean0 = emailValidator0.isValidUser("i|-No5o@3p1.wLs}ydO");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EmailValidator emailValidator0 = EmailValidator.getInstance2(true);
      boolean boolean0 = emailValidator0.isValidUser((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance1(true);
      EmailValidator emailValidator0 = new EmailValidator(1, false, true, domainValidator0);
      boolean boolean0 = emailValidator0.isValidDomain("tunes");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DomainValidator domainValidator0 = new DomainValidator(3174, (List<DomainValidator.Item>) null, false);
      EmailValidator emailValidator0 = new EmailValidator((-3151), false, true, domainValidator0);
      boolean boolean0 = emailValidator0.isValidDomain(".");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DomainValidator.Item domainValidator_Item0 = mock(DomainValidator.Item.class, new ViolatedAssumptionAnswer());
      List<DomainValidator.Item> list0 = List.of(domainValidator_Item0);
      DomainValidator domainValidator0 = new DomainValidator(2260, list0, false);
      EmailValidator emailValidator0 = new EmailValidator(2260, true, true, domainValidator0);
      boolean boolean0 = emailValidator0.isValidDomain("xn--j1amh");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EmailValidator emailValidator0 = EmailValidator.getInstance1(false, false);
      // Undeclared exception!
      try { 
        emailValidator0.isValidDomain("[]");
       //  fail("Expecting exception: IllegalStateException");
       // Unstable assertion
      } catch(IllegalStateException e) {
         //
         // No match found
         //
         verifyException("java.util.regex.Matcher", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EmailValidator emailValidator0 = EmailValidator.getInstance1(true, true);
      boolean boolean0 = emailValidator0.isValidDomain("NYtNJ:.");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EmailValidator emailValidator0 = EmailValidator.getInstance1(false, false);
      // Undeclared exception!
      try { 
        emailValidator0.isValid("p{Cntrl}()<>@,;:'\\\".[]");
       //  fail("Expecting exception: IllegalStateException");
       // Unstable assertion
      } catch(IllegalStateException e) {
         //
         // No match found
         //
         verifyException("java.util.regex.Matcher", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      EmailValidator emailValidator0 = EmailValidator.getInstance1(false, false);
      boolean boolean0 = emailValidator0.isValid(".");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      EmailValidator emailValidator0 = EmailValidator.getInstance1(false, false);
      boolean boolean0 = emailValidator0.isValid((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance0();
      EmailValidator emailValidator0 = null;
      try {
        emailValidator0 = new EmailValidator(0, true, false, domainValidator0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // DomainValidator must agree with allowLocal setting
         //
         verifyException("org.apache.commons.validator.routines.EmailValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      EmailValidator emailValidator0 = null;
      try {
        emailValidator0 = new EmailValidator(0, true, true, (DomainValidator) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // DomainValidator cannot be null
         //
         verifyException("org.apache.commons.validator.routines.EmailValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DomainValidator domainValidator0 = DomainValidator.getInstance0();
      EmailValidator emailValidator0 = new EmailValidator(0, false, false, domainValidator0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      EmailValidator emailValidator0 = EmailValidator.getInstance1(false, true);
      assertNotNull(emailValidator0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      EmailValidator emailValidator0 = EmailValidator.getInstance1(true, false);
      assertNotNull(emailValidator0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      EmailValidator emailValidator0 = EmailValidator.getInstance1(true, true);
      boolean boolean0 = emailValidator0.isValid("/");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      EmailValidator emailValidator0 = EmailValidator.EmailValidator0(true);
      assertNotNull(emailValidator0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      EmailValidator emailValidator0 = EmailValidator.getInstance0();
      boolean boolean0 = emailValidator0.isValidDomain("?U$M4N}MH\"Vy#_N$k");
      assertFalse(boolean0);
  }
}
