/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 22:06:56 GMT 2025
 */

package org.apache.commons.validator.routines;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.text.DecimalFormat;
import java.util.Locale;
import org.apache.commons.validator.routines.IntegerValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IntegerValidator_ESTest extends IntegerValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      Integer integer0 = new Integer((-1));
      boolean boolean0 = integerValidator0.maxValue1(integer0, (-1));
      assertTrue(integerValidator0.isStrict());
      assertTrue(boolean0);
      assertEquals(0, integerValidator0.getFormatType());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.getInstance();
      boolean boolean0 = integerValidator0.isInRange0(0, 0, 2);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      Locale locale0 = Locale.TAIWAN;
      Integer integer0 = integerValidator0.validate3("9", "", locale0);
      assertNotNull(integer0);
      assertTrue(integerValidator0.isStrict());
      assertEquals(9, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.getInstance();
      Locale locale0 = Locale.FRENCH;
      Integer integer0 = integerValidator0.validate3("", "", locale0);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      Locale locale0 = Locale.ENGLISH;
      Integer integer0 = integerValidator0.validate3("-1,064", (String) null, locale0);
      assertNotNull(integer0);
      assertTrue(integerValidator0.isStrict());
      assertEquals((-1064), (int)integer0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.getInstance();
      Locale locale0 = Locale.ROOT;
      Integer integer0 = integerValidator0.validate2("6", locale0);
      assertNotNull(integer0);
      assertEquals(6, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      Locale locale0 = Locale.JAPAN;
      integerValidator0.validate2("hz!a/tCxmXD6[!DPf=", locale0);
      assertTrue(integerValidator0.isStrict());
      assertEquals(0, integerValidator0.getFormatType());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.getInstance();
      Integer integer0 = integerValidator0.validate1("^-%wA}gCD~)>Z70", "^-%wA}gCD~)>Z70");
      assertEquals(0, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      Integer integer0 = integerValidator0.validate1("1", "");
      assertTrue(integerValidator0.isStrict());
      assertEquals(1, (int)integer0);
      assertNotNull(integer0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      integerValidator0.validate1("Qs/)C@1V/&<vJvU", "Qs/)C@1V/&<vJvU");
      assertTrue(integerValidator0.isStrict());
      assertEquals(0, integerValidator0.getFormatType());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      IntegerValidator integerValidator0 = new IntegerValidator(false, 2236);
      Integer integer0 = integerValidator0.validate0("0\\]/$F9cb2J");
      assertEquals(0, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      IntegerValidator integerValidator0 = new IntegerValidator(false, (-1910));
      Integer integer0 = integerValidator0.validate0("9O#ItU4u");
      assertNotNull(integer0);
      assertEquals(9, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      boolean boolean0 = integerValidator0.minValue1((Integer) 1, 1);
      assertTrue(integerValidator0.isStrict());
      assertTrue(boolean0);
      assertEquals(0, integerValidator0.getFormatType());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      boolean boolean0 = integerValidator0.minValue1((Integer) integerValidator0.CURRENCY_FORMAT, 2);
      assertEquals(0, integerValidator0.getFormatType());
      assertFalse(boolean0);
      assertTrue(integerValidator0.isStrict());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      boolean boolean0 = integerValidator0.maxValue1((Integer) 0, 2);
      assertTrue(boolean0);
      assertTrue(integerValidator0.isStrict());
      assertEquals(0, integerValidator0.getFormatType());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      boolean boolean0 = integerValidator0.maxValue1((Integer) 2, 0);
      assertTrue(integerValidator0.isStrict());
      assertFalse(boolean0);
      assertEquals(0, integerValidator0.getFormatType());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      Integer integer0 = new Integer((-630));
      boolean boolean0 = integerValidator0.isInRange1(integer0, (-630), (-630));
      assertTrue(boolean0);
      assertTrue(integerValidator0.isStrict());
      assertEquals(0, integerValidator0.getFormatType());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      // Undeclared exception!
      try { 
        integerValidator0.validate3("8,8LT,}Pb6", "8,8LT,}Pb6", (Locale) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Malformed pattern \"8,8LT,}Pb6\"
         //
         verifyException("java.text.DecimalFormat", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      // Undeclared exception!
      try { 
        integerValidator0.validate1("org.apache.commons.validator.routines.AbstractFormatValidator", "org.apache.commons.validator.routines.AbstractFormatValidator");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Multiple decimal separators in pattern \"org.apache.commons.validator.routines.AbstractFormatValidator\"
         //
         verifyException("java.text.DecimalFormat", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      IntegerValidator integerValidator0 = new IntegerValidator(false, 0);
      // Undeclared exception!
      try { 
        integerValidator0.isInRange1((Integer) null, 415, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.routines.IntegerValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      boolean boolean0 = integerValidator0.isInRange0(1, 1, 0);
      assertFalse(boolean0);
      assertTrue(integerValidator0.isStrict());
      assertEquals(0, integerValidator0.getFormatType());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      IntegerValidator integerValidator0 = new IntegerValidator(false, 0);
      boolean boolean0 = integerValidator0.isInRange0((-2076), (-1128), 2206);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      Locale locale0 = Locale.PRC;
      DecimalFormat decimalFormat0 = (DecimalFormat)integerValidator0.getFormat1(locale0);
      integerValidator0.processParsedValue((Object) null, decimalFormat0);
      assertTrue(integerValidator0.isStrict());
      assertEquals(0, decimalFormat0.getMinimumFractionDigits());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      IntegerValidator integerValidator0 = new IntegerValidator(false, (-27));
      boolean boolean0 = integerValidator0.maxValue0((-163), 0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      boolean boolean0 = integerValidator0.maxValue0(1, 0);
      assertEquals(0, integerValidator0.getFormatType());
      assertFalse(boolean0);
      assertTrue(integerValidator0.isStrict());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      boolean boolean0 = integerValidator0.minValue0(2680, 0);
      assertTrue(boolean0);
      assertEquals(0, integerValidator0.getFormatType());
      assertTrue(integerValidator0.isStrict());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      boolean boolean0 = integerValidator0.minValue0(0, 1);
      assertFalse(boolean0);
      assertEquals(0, integerValidator0.getFormatType());
      assertTrue(integerValidator0.isStrict());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      boolean boolean0 = integerValidator0.isInRange0(791, 2, 791);
      assertTrue(integerValidator0.isStrict());
      assertTrue(boolean0);
      assertEquals(0, integerValidator0.getFormatType());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      boolean boolean0 = integerValidator0.isInRange1((Integer) 0, 1, 1);
      assertFalse(boolean0);
      assertTrue(integerValidator0.isStrict());
      assertEquals(0, integerValidator0.getFormatType());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.getInstance();
      Locale locale0 = Locale.CANADA_FRENCH;
      Integer integer0 = integerValidator0.validate2("0", locale0);
      assertEquals(0, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.getInstance();
      // Undeclared exception!
      try { 
        integerValidator0.minValue1((Integer) null, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.routines.IntegerValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.getInstance();
      Integer integer0 = integerValidator0.validate0("");
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.getInstance();
      // Undeclared exception!
      try { 
        integerValidator0.maxValue1((Integer) null, 650);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.validator.routines.IntegerValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      IntegerValidator integerValidator0 = new IntegerValidator(false, 2236);
      Locale locale0 = Locale.CANADA;
      Integer integer0 = integerValidator0.validate3("0\\]/$F9cb2J", "0\\]/$F9cb2J", locale0);
      assertEquals(0, (int)integer0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.getInstance();
      Integer integer0 = integerValidator0.validate1("-3", (String) null);
      assertNotNull(integer0);
      assertEquals((-3), (int)integer0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      IntegerValidator integerValidator0 = IntegerValidator.IntegerValidator1();
      boolean boolean0 = integerValidator0.isInRange1((Integer) integerValidator0.PERCENT_FORMAT, 0, (-926));
      assertTrue(integerValidator0.isStrict());
      assertEquals(0, integerValidator0.getFormatType());
      assertFalse(boolean0);
  }
}
