/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 21:33:24 GMT 2025
 */

package org.apache.commons.validator.routines;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.validator.routines.ISBNValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ISBNValidator_ESTest extends ISBNValidator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ISBNValidator iSBNValidator0 = new ISBNValidator(false);
      // Undeclared exception!
      try { 
        iSBNValidator0.convertToISBN13(" =fJrc<vS");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid length 8 for '=fJrc<vS'
         //
         verifyException("org.apache.commons.validator.routines.ISBNValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ISBNValidator iSBNValidator0 = ISBNValidator.getInstance0();
      // Undeclared exception!
      try { 
        iSBNValidator0.convertToISBN13("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid length 0 for ''
         //
         verifyException("org.apache.commons.validator.routines.ISBNValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ISBNValidator iSBNValidator0 = ISBNValidator.getInstance0();
      String string0 = iSBNValidator0.validateISBN13(":p`g!F3`%.,H]SXP");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ISBNValidator iSBNValidator0 = ISBNValidator.getInstance0();
      String string0 = iSBNValidator0.validateISBN10("");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ISBNValidator iSBNValidator0 = ISBNValidator.getInstance1(false);
      boolean boolean0 = iSBNValidator0.isValidISBN13((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ISBNValidator iSBNValidator0 = ISBNValidator.getInstance0();
      boolean boolean0 = iSBNValidator0.isValidISBN10((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ISBNValidator iSBNValidator0 = ISBNValidator.getInstance0();
      // Undeclared exception!
      try { 
        iSBNValidator0.convertToISBN13("m|&#tu'N. ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Check digit error for 'm|&#tu'N.' - Invalid Character[4] = 'm'
         //
         verifyException("org.apache.commons.validator.routines.ISBNValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ISBNValidator iSBNValidator0 = new ISBNValidator(true);
      // Undeclared exception!
      try { 
        iSBNValidator0.convertToISBN13("^(978|979)(?:(d{10})|(?:(?:-|s)(d{1,5})(?:-|s)(d{1,7})(?:-|s)(d{1,6})(?:-|s)([0-9])))$");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid length 86 for '^(978|979)(?:(d{10})|(?:(?:-|s)(d{1,5})(?:-|s)(d{1,7})(?:-|s)(d{1,6})(?:-|s)([0-9])))$'
         //
         verifyException("org.apache.commons.validator.routines.ISBNValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ISBNValidator iSBNValidator0 = ISBNValidator.getInstance1(true);
      assertNotNull(iSBNValidator0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ISBNValidator iSBNValidator0 = ISBNValidator.getInstance1(false);
      String string0 = iSBNValidator0.validate("");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ISBNValidator iSBNValidator0 = ISBNValidator.ISBNValidator1();
      assertNotNull(iSBNValidator0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ISBNValidator iSBNValidator0 = new ISBNValidator(true);
      boolean boolean0 = iSBNValidator0.isValid("k_Z!");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ISBNValidator iSBNValidator0 = ISBNValidator.getInstance0();
      String string0 = iSBNValidator0.convertToISBN13((String) null);
      assertNull(string0);
  }
}
