/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 18:59:35 GMT 2025
 */

package org.apache.commons.fileupload.util.mime;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.UnsupportedEncodingException;
import org.apache.commons.fileupload.util.mime.MimeUtility;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MimeUtility_ESTest extends MimeUtility_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        MimeUtility.decodeText((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.fileupload.util.mime.MimeUtility", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      try { 
        MimeUtility.decodeText("=?=?=?=?=?=?");
        fail("Expecting exception: UnsupportedEncodingException");
      
      } catch(UnsupportedEncodingException e) {
         //
         // Invalid RFC 2047 encoding
         //
         verifyException("org.apache.commons.fileupload.util.mime.MimeUtility", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = MimeUtility.decodeText("=?~?=?=?{X=1=");
      assertEquals("=?~?=?=?{X=1=", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = MimeUtility.decodeText("=?=?");
      assertEquals("=?=?", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String string0 = MimeUtility.decodeText("=?");
      assertEquals("=?", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String string0 = MimeUtility.decodeText("<^/=?kur:0v]/1Nn G ");
      assertEquals("<^/=?kur:0v]/1Nn G", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String string0 = MimeUtility.decodeText("=?=?=??=?=A");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String string0 = MimeUtility.decodeText("Invalid Base64 input: incorrect padding, first two bytes cannot be padding");
      assertEquals("Invalid Base64 input: incorrect padding, first two bytes cannot be padding", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      try { 
        MimeUtility.decodeText("=??Q?m?={");
        fail("Expecting exception: UnsupportedEncodingException");
      
      } catch(UnsupportedEncodingException e) {
         //
         // Invalid RFC 2047 encoding
         //
         verifyException("org.apache.commons.fileupload.util.mime.MimeUtility", e);
      }
  }
}
