/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 19:20:50 GMT 2025
 */

package org.apache.commons.graph.elo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.graph.elo.DefaultKFactorBuilder;
import org.apache.commons.graph.elo.GameResult;
import org.apache.commons.graph.elo.PlayersRank;
import org.apache.commons.graph.model.DirectedMutableGraph;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DefaultKFactorBuilder_ESTest extends DefaultKFactorBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DirectedMutableGraph<GameResult, GameResult> directedMutableGraph0 = new DirectedMutableGraph<GameResult, GameResult>();
      GameResult gameResult0 = GameResult.WIN;
      directedMutableGraph0.addVertex(gameResult0);
      GameResult gameResult1 = GameResult.DRAW;
      directedMutableGraph0.addVertex(gameResult1);
      directedMutableGraph0.containsVertex(gameResult1);
      Double double0 = new Double(0.0);
      PlayersRank<GameResult> playersRank0 = (PlayersRank<GameResult>) mock(PlayersRank.class, new ViolatedAssumptionAnswer());
      doReturn((Double) null).when(playersRank0).getRanking(any(org.apache.commons.graph.elo.GameResult.class));
      DefaultKFactorBuilder<GameResult> defaultKFactorBuilder0 = new DefaultKFactorBuilder<GameResult>(directedMutableGraph0, playersRank0);
      directedMutableGraph0.addEdge(gameResult1, gameResult0, gameResult0);
      // Undeclared exception!
      try { 
        defaultKFactorBuilder0.withDefaultKFactor();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.graph.elo.DefaultKFactorBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DirectedMutableGraph<GameResult, GameResult> directedMutableGraph0 = new DirectedMutableGraph<GameResult, GameResult>();
      GameResult gameResult0 = GameResult.WIN;
      directedMutableGraph0.addVertex(gameResult0);
      Double double0 = new Double(1735.947719834654);
      Double double1 = new Double(0.0);
      PlayersRank<GameResult> playersRank0 = (PlayersRank<GameResult>) mock(PlayersRank.class, new ViolatedAssumptionAnswer());
      doReturn(double0, double1, double0, double1).when(playersRank0).getRanking(any(org.apache.commons.graph.elo.GameResult.class));
      DefaultKFactorBuilder<GameResult> defaultKFactorBuilder0 = new DefaultKFactorBuilder<GameResult>(directedMutableGraph0, playersRank0);
      directedMutableGraph0.addEdge(gameResult0, gameResult0, gameResult0);
      defaultKFactorBuilder0.withDefaultKFactor();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DirectedMutableGraph<GameResult, GameResult> directedMutableGraph0 = new DirectedMutableGraph<GameResult, GameResult>();
      GameResult gameResult0 = GameResult.WIN;
      directedMutableGraph0.addVertex(gameResult0);
      PlayersRank<GameResult> playersRank0 = (PlayersRank<GameResult>) mock(PlayersRank.class, new ViolatedAssumptionAnswer());
      doReturn((Double) null).when(playersRank0).getRanking(any(org.apache.commons.graph.elo.GameResult.class));
      DefaultKFactorBuilder<GameResult> defaultKFactorBuilder0 = new DefaultKFactorBuilder<GameResult>(directedMutableGraph0, playersRank0);
      directedMutableGraph0.addEdge(gameResult0, gameResult0, gameResult0);
      // Undeclared exception!
      try { 
        defaultKFactorBuilder0.withKFactor(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.graph.elo.DefaultKFactorBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DirectedMutableGraph<GameResult, GameResult> directedMutableGraph0 = new DirectedMutableGraph<GameResult, GameResult>();
      GameResult gameResult0 = GameResult.WIN;
      directedMutableGraph0.addVertex(gameResult0);
      PlayersRank<GameResult> playersRank0 = (PlayersRank<GameResult>) mock(PlayersRank.class, new ViolatedAssumptionAnswer());
      DefaultKFactorBuilder<GameResult> defaultKFactorBuilder0 = new DefaultKFactorBuilder<GameResult>(directedMutableGraph0, playersRank0);
      defaultKFactorBuilder0.withKFactor(0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DirectedMutableGraph<GameResult, GameResult> directedMutableGraph0 = new DirectedMutableGraph<GameResult, GameResult>();
      GameResult gameResult0 = GameResult.WIN;
      directedMutableGraph0.addVertex(gameResult0);
      directedMutableGraph0.containsVertex(gameResult0);
      Double double0 = new Double(0.0);
      Double double1 = new Double(0.0);
      PlayersRank<GameResult> playersRank0 = (PlayersRank<GameResult>) mock(PlayersRank.class, new ViolatedAssumptionAnswer());
      doReturn((Double) null).when(playersRank0).getRanking(any(org.apache.commons.graph.elo.GameResult.class));
      DefaultKFactorBuilder<GameResult> defaultKFactorBuilder0 = new DefaultKFactorBuilder<GameResult>(directedMutableGraph0, playersRank0);
      GameResult gameResult1 = GameResult.DRAW;
      directedMutableGraph0.addEdge(gameResult0, gameResult1, gameResult0);
      // Undeclared exception!
      try { 
        defaultKFactorBuilder0.withDefaultKFactor();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.graph.elo.DefaultKFactorBuilder", e);
      }
  }
}
