/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 19:27:48 GMT 2025
 */

package org.fusesource.jansi;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.fusesource.jansi.AnsiType;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AnsiType_ESTest extends AnsiType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AnsiType[] ansiTypeArray0 = AnsiType.values();
      assertEquals(5, ansiTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AnsiType ansiType0 = AnsiType.valueOf("Native");
      assertEquals(AnsiType.Native, ansiType0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AnsiType ansiType0 = AnsiType.VirtualTerminal;
      String string0 = ansiType0.getDescription();
      assertEquals("Supported through windows virtual terminal", string0);
  }
}
