/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 19:23:29 GMT 2025
 */

package org.fusesource.jansi;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.fusesource.jansi.Ansi;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Ansi$Color_ESTest extends Ansi$Color_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ansi.Color ansi_Color0 = Ansi.Color.BLUE;
      int int0 = ansi_Color0.bgBright();
      assertEquals(104, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Ansi.Color ansi_Color0 = Ansi.Color.RED;
      int int0 = ansi_Color0.fg();
      assertEquals(31, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Ansi.Color ansi_Color0 = Ansi.Color.GREEN;
      String string0 = ansi_Color0.toString();
      assertEquals("GREEN", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Ansi.Color ansi_Color0 = Ansi.Color.RED;
      int int0 = ansi_Color0.value();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Ansi.Color ansi_Color0 = Ansi.Color.RED;
      int int0 = ansi_Color0.bg();
      assertEquals(41, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Ansi.Color ansi_Color0 = Ansi.Color.BLUE;
      int int0 = ansi_Color0.fgBright();
      assertEquals(94, int0);
  }
}
