/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 21:25:40 GMT 2025
 */

package org.apache.commons.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.validator.Arg;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Arg_ESTest extends Arg_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Arg arg0 = new Arg();
      arg0.setBundle("Arg: name=j  key=null  position=-585  bundle=null  resource=true\n");
      String string0 = arg0.toString();
      assertEquals("Arg: name=null  key=null  position=-1  bundle=Arg: name=j  key=null  position=-585  bundle=null  resource=true\n  resource=true\n", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Arg arg0 = new Arg();
      arg0.setName("j");
      String string0 = arg0.toString();
      assertEquals("Arg: name=j  key=null  position=-1  bundle=null  resource=true\n", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Arg arg0 = new Arg();
      assertTrue(arg0.isResource());
      
      arg0.setResource(false);
      assertFalse(arg0.isResource());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Arg arg0 = new Arg();
      assertTrue(arg0.isResource());
      
      arg0.resource = false;
      arg0.isResource();
      assertEquals((-1), arg0.getPosition());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Arg arg0 = new Arg();
      arg0.position = 4488;
      int int0 = arg0.getPosition();
      assertEquals(4488, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Arg arg0 = new Arg();
      arg0.setName("");
      String string0 = arg0.getName();
      assertTrue(arg0.isResource());
      assertNotNull(string0);
      assertEquals((-1), arg0.getPosition());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Arg arg0 = new Arg();
      arg0.key = "`.4e}";
      String string0 = arg0.getKey();
      assertEquals((-1), arg0.getPosition());
      assertTrue(arg0.isResource());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Arg arg0 = new Arg();
      arg0.setKey("");
      String string0 = arg0.getKey();
      assertTrue(arg0.isResource());
      assertEquals((-1), arg0.getPosition());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Arg arg0 = new Arg();
      arg0.setBundle("");
      String string0 = arg0.getBundle();
      assertTrue(arg0.isResource());
      assertEquals((-1), arg0.getPosition());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Arg arg0 = new Arg();
      int int0 = arg0.getPosition();
      assertEquals((-1), int0);
      assertTrue(arg0.isResource());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Arg arg0 = new Arg();
      arg0.setName("j");
      String string0 = arg0.getName();
      assertEquals((-1), arg0.getPosition());
      assertTrue(arg0.isResource());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Arg arg0 = new Arg();
      arg0.getBundle();
      assertEquals((-1), arg0.getPosition());
      assertTrue(arg0.isResource());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Arg arg0 = new Arg();
      arg0.getName();
      assertEquals((-1), arg0.getPosition());
      assertTrue(arg0.isResource());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Arg arg0 = new Arg();
      Arg arg1 = (Arg)arg0.clone();
      assertEquals((-1), arg1.getPosition());
      assertTrue(arg1.isResource());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Arg arg0 = new Arg();
      boolean boolean0 = arg0.isResource();
      assertEquals((-1), arg0.getPosition());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Arg arg0 = new Arg();
      arg0.getKey();
      assertEquals((-1), arg0.getPosition());
      assertTrue(arg0.isResource());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Arg arg0 = new Arg();
      assertEquals((-1), arg0.getPosition());
      
      arg0.setPosition(0);
      int int0 = arg0.getPosition();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Arg arg0 = new Arg();
      arg0.setBundle("Arg: name=j  key=null  position=-585  bundle=null  resource=true\n");
      String string0 = arg0.getBundle();
      assertTrue(arg0.isResource());
      assertNotNull(string0);
      assertEquals((-1), arg0.getPosition());
  }
}
